// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olankshsflmkfnlqyumf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sYW5rc2hzZmxta2ZubHF5dW1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDc5MjMsImV4cCI6MjA3MDA4MzkyM30.pYE2CLHCUFiOEVXFcmXuromxJ3V05SHQodQjZwS3efs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});